# Generated by Django 4.0 on 2022-02-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.customeusers'),
        ),
    ]
