# Generated by Django 4.0 on 2022-02-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='bio',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
