# Generated by Django 4.0 on 2022-02-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
