# Generated by Django 4.0 on 2022-02-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='profile_pic',
            field=models.ImageField(default='default_2.jpg', upload_to='profile_pic'),
        ),
    ]
