# Generated by Django 4.0 on 2022-02-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_profile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_profile',
        ),
    ]
