# Generated by Django 4.0 on 2022-02-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_department_year_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Bio',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Dept',
            field=models.CharField(blank=True, choices=[('bca', 'BCA'), ('bamalayalam', 'B.A Malayalam'), ('baenglish', 'B.A English'), ('bscchemistry', 'BSC Chemistry')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Designation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Friends',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Posts',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Yr',
            field=models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
