# Generated by Django 4.0 on 2022-02-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
