# Generated by Django 4.0 on 2022-03-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=1000)),
                ('Picture', models.ImageField(blank=True, upload_to='posts')),
                ('is_timeline', models.BooleanField(default=True)),
                ('is_p_cell', models.BooleanField(default=False)),
                ('is_notice', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
