# Generated by Django 4.0 on 2022-03-16 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customeusers'),
        ),
    ]
