# Generated by Django 4.0 on 2022-02-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
