# Generated by Django 4.0 on 2022-02-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_posts_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_timeline',
            field=models.BooleanField(default=True),
        ),
    ]
