# Generated by Django 4.0 on 2022-02-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_posts_is_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
