# Generated by Django 4.0.3 on 2022-04-12 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatspace',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
